apiVersion: v1
kind: ConfigMap
metadata:
  name: java-microservice-config
  labels:
    app.kubernetes.io/name: java-microservice
    app.kubernetes.io/instance: java-microservice
data:
  application.yml: |
    server:
      port: 8080
      shutdown: graceful
    spring:
      application:
        name: java-microservice
      profiles:
        active: kubernetes
    management:
      endpoints:
        web:
          exposure:
            include: health,info,prometheus,metrics
      endpoint:
        health:
          show-details: always
      health:
        readinessState:
          enabled: true
        livenessState:
          enabled: true
      server:
        port: 8080
    logging:
      level:
        com.example.demo: INFO
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"